# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ltegui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1443, 862)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(261, 900000))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(261, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(261, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonPSD = QtWidgets.QPushButton(self.widget_2)
        self.buttonPSD.setObjectName("buttonPSD")
        self.gridLayout.addWidget(self.buttonPSD, 1, 3, 1, 1)
        self.buttonForward = QtWidgets.QPushButton(self.widget_2)
        self.buttonForward.setObjectName("buttonForward")
        self.gridLayout.addWidget(self.buttonForward, 0, 1, 1, 1)
        self.buttonGo_to = QtWidgets.QPushButton(self.widget_2)
        self.buttonGo_to.setObjectName("buttonGo_to")
        self.gridLayout.addWidget(self.buttonGo_to, 1, 0, 1, 1)
        self.buttonSet_interval = QtWidgets.QPushButton(self.widget_2)
        self.buttonSet_interval.setObjectName("buttonSet_interval")
        self.gridLayout.addWidget(self.buttonSet_interval, 1, 1, 1, 1)
        self.buttonReset_Ticks = QtWidgets.QPushButton(self.widget_2)
        self.buttonReset_Ticks.setObjectName("buttonReset_Ticks")
        self.gridLayout.addWidget(self.buttonReset_Ticks, 1, 4, 1, 1)
        self.buttonBackwards = QtWidgets.QPushButton(self.widget_2)
        self.buttonBackwards.setObjectName("pushButton")
        self.gridLayout.addWidget(self.buttonBackwards, 0, 0, 1, 1)
        self.buttonSave_Event = QtWidgets.QPushButton(self.widget_2)
        self.buttonSave_Event.setObjectName("buttonSave_Event")
        self.gridLayout.addWidget(self.buttonSave_Event, 0, 3, 1, 1)
        self.buttonWaveform = QtWidgets.QPushButton(self.widget_2)
        self.buttonWaveform.setObjectName("buttonWaveform")
        self.gridLayout.addWidget(self.buttonWaveform, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 2, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textTickInfo = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textTickInfo.setObjectName("textTickInfo")
        self.verticalLayout_3.addWidget(self.textTickInfo)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.eventWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.eventWidget.setObjectName("eventWidget")
        self.verticalLayout.addWidget(self.eventWidget)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.widget)
        # self.widgetLTE = QtWidgets.QWidget(self.centralwidget)
        # self.widgetLTE.setObjectName("widgetLTE")
        # self.horizontalLayout.addWidget(self.widgetLTE)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1443, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Ticks = QtWidgets.QMenu(self.menubar)
        self.menu_Ticks.setObjectName("menu_Ticks")
        self.menu_LDE = QtWidgets.QMenu(self.menubar)
        self.menu_LDE.setObjectName("menu_LDE")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLTE_info = QtWidgets.QAction(MainWindow)
        self.actionLTE_info.setObjectName("actionLTE_info")
        self.actionGo_to = QtWidgets.QAction(MainWindow)
        self.actionGo_to.setObjectName("actionGo_to")
        self.actionSet_interval = QtWidgets.QAction(MainWindow)
        self.actionSet_interval.setObjectName("actionSet_interval")
        self.actionSave_Figure = QtWidgets.QAction(MainWindow)
        self.actionSave_Figure.setObjectName("actionSave_Figure")
        self.actionReset_Ticks = QtWidgets.QAction(MainWindow)
        self.actionReset_Ticks.setObjectName("actionReset_Ticks")
        self.actionWaveform = QtWidgets.QAction(MainWindow)
        self.actionWaveform.setObjectName("actionWaveform")
        self.actionPSD = QtWidgets.QAction(MainWindow)
        self.actionPSD.setObjectName("actionPSD")
        self.actionSave_Event = QtWidgets.QAction(MainWindow)
        self.actionSave_Event.setObjectName("actionSave_Event")
        self.actionOpen_Database = QtWidgets.QAction(MainWindow)
        self.actionOpen_Database.setObjectName("actionOpen_Database")
        self.actionScatter = QtWidgets.QAction(MainWindow)
        self.actionScatter.setObjectName("actionScatter")
        self.actionPlot = QtWidgets.QAction(MainWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.actionPlotEvent = QtWidgets.QAction(MainWindow)
        self.actionPlotEvent.setObjectName("actionRemove")
        self.menu_File.addAction(self.actionLTE_info)
        self.menu_File.addAction(self.actionGo_to)
        self.menu_File.addAction(self.actionSet_interval)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave_Figure)
        self.menu_Ticks.addAction(self.actionReset_Ticks)
        self.menu_Ticks.addAction(self.actionWaveform)
        self.menu_Ticks.addAction(self.actionPSD)
        self.menu_Ticks.addSeparator()
        self.menu_Ticks.addAction(self.actionSave_Event)
        self.menu_LDE.addAction(self.actionOpen_Database)
        self.menu_LDE.addAction(self.actionScatter)
        self.menu_LDE.addAction(self.actionPlot)
        self.menu_LDE.addSeparator()
        self.menu_LDE.addAction(self.actionPlotEvent)
        self.menu_LDE.addAction(self.actionRemove)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Ticks.menuAction())
        self.menubar.addAction(self.menu_LDE.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LTE Plot"))
        self.buttonPSD.setText(_translate("MainWindow", "PSD"))
        self.buttonForward.setText(_translate("MainWindow", "-->"))
        self.buttonGo_to.setText(_translate("MainWindow", "Time"))
        self.buttonSet_interval.setText(_translate("MainWindow", "Delta"))
        self.buttonReset_Ticks.setText(_translate("MainWindow", "Reset"))
        self.buttonBackwards.setText(_translate("MainWindow", "<--"))
        self.buttonSave_Event.setText(_translate("MainWindow", "Save"))
        self.buttonWaveform.setText(_translate("MainWindow", "Plot"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Info"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Events"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Ticks.setTitle(_translate("MainWindow", "&Tools"))
        self.menu_LDE.setTitle(_translate("MainWindow", "&LDE"))
        self.actionLTE_info.setText(_translate("MainWindow", "LTE info"))
        self.actionGo_to.setText(_translate("MainWindow", "Go to..."))
        self.actionSet_interval.setText(_translate("MainWindow", "Set interval"))
        self.actionSave_Figure.setText(_translate("MainWindow", "Save Figure"))
        self.actionReset_Ticks.setText(_translate("MainWindow", "Reset Ticks"))
        self.actionWaveform.setText(_translate("MainWindow", "Waveform"))
        self.actionPSD.setText(_translate("MainWindow", "PSD"))
        self.actionSave_Event.setText(_translate("MainWindow", "Save Event"))
        self.actionOpen_Database.setText(_translate("MainWindow", "Open Database"))
        self.actionScatter.setText(_translate("MainWindow", "Scatter..."))
        self.actionPlot.setText(_translate("MainWindow", "Activity..."))
        self.actionRemove.setText(_translate("MainWindow", "Remove..."))
        self.actionPlotEvent.setText(_translate("MainWindow", "Plot Event..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

