# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ldegui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1700, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 22))
        self.menubar.setObjectName("menubar")
        self.menu_Database = QtWidgets.QMenu(self.menubar)
        self.menu_Database.setObjectName("menu_Database")
        self.menu_Event = QtWidgets.QMenu(self.menubar)
        self.menu_Event.setObjectName("menu_Event")
        self.menu_Plots = QtWidgets.QMenu(self.menubar)
        self.menu_Plots.setObjectName("menu_Plots")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRelabel = QtWidgets.QAction(MainWindow)
        self.actionRelabel.setObjectName("actionRelabel")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.actionPlotPolar = QtWidgets.QAction(MainWindow)
        self.actionPlotPolar.setObjectName("actionPlotPolar")
        self.actionSet_Starttime = QtWidgets.QAction(MainWindow)
        self.actionSet_Starttime.setObjectName("actionSet_Starttime")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGo_to_ID = QtWidgets.QAction(MainWindow)
        self.actionGo_to_ID.setObjectName("actionGo_to_ID")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionFilter = QtWidgets.QAction(MainWindow)
        self.actionFilter.setObjectName("actionFilter")
        self.actionPlot_Scatter = QtWidgets.QAction(MainWindow)
        self.actionPlot_Scatter.setObjectName("actionPlot_Scatter")
        self.actionActivity = QtWidgets.QAction(MainWindow)
        self.actionActivity.setObjectName("actionActivity")
        self.actionOpen_LTE = QtWidgets.QAction(MainWindow)
        self.actionOpen_LTE.setObjectName("actionOpen_LTE")
        self.actionODP = QtWidgets.QAction(MainWindow, checkable=True)
        self.actionODP.setObjectName("actionODP")
        self.actionFull_Range = QtWidgets.QAction(MainWindow, checkable=True)
        self.actionFull_Range.setObjectName("actionContinuous")
        self.actionStep_Range = QtWidgets.QAction(MainWindow, checkable=True)
        self.actionStep_Range.setObjectName("actionStep_Range")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionPSD = QtWidgets.QAction(MainWindow)
        self.actionPSD.setObjectName("actionPSD")
        self.actionPlot_3D = QtWidgets.QAction(MainWindow)
        self.actionPlot_3D.setObjectName("actionPlot_3D")
        self.menu_Database.addAction(self.action_Open)
        self.menu_Database.addSeparator()
        self.menu_Database.addAction(self.actionNext)
        self.menu_Database.addAction(self.actionPrevious)
        self.menu_Database.addAction(self.actionGo_to_ID)
        self.menu_Database.addSeparator()
        self.menu_Database.addAction(self.actionFilter)
        self.menu_Database.addAction(self.actionReset)
        self.menu_Database.addSeparator()
        self.menu_Database.addAction(self.actionExit)
        self.menu_Event.addAction(self.actionOpen_LTE)
        self.menu_Event.addSeparator()
        self.menu_Event.addAction(self.actionRelabel)
        self.menu_Event.addAction(self.actionSet_Starttime)
        self.menu_Event.addSeparator()
        self.menu_Event.addAction(self.actionPlotPolar)
        self.menu_Event.addAction(self.actionRemove)
        self.menu_Plots.addAction(self.actionPlot_Scatter)
        self.menu_Plots.addAction(self.actionActivity)
        self.menu_Plots.addSeparator()
        self.menu_Plots.addAction(self.actionPlot_3D)
        self.menu_View.addAction(self.actionODP)
        self.menu_View.addAction(self.actionFull_Range)
        self.menu_View.addAction(self.actionStep_Range)
        self.menubar.addAction(self.menu_Database.menuAction())
        self.menubar.addAction(self.menu_Event.menuAction())
        self.menubar.addAction(self.menu_Plots.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LDE Plot"))
        self.menu_Database.setTitle(_translate("MainWindow", "&Database"))
        self.menu_Event.setTitle(_translate("MainWindow", "&Event"))
        self.menu_Plots.setTitle(_translate("MainWindow", "&Plots"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.actionRelabel.setText(_translate("MainWindow", "Relabel"))
        self.actionRemove.setText(_translate("MainWindow", "Remove"))
        self.actionPlotPolar.setText(_translate("MainWindow", "Plot Polar"))
        self.actionSet_Starttime.setText(_translate("MainWindow", "Set Starttime"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionGo_to_ID.setText(_translate("MainWindow", "Go to ID..."))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionFilter.setText(_translate("MainWindow", "Filter..."))
        self.actionPlot_Scatter.setText(_translate("MainWindow", "Scatter..."))
        self.actionActivity.setText(_translate("MainWindow", "Activity..."))
        self.actionOpen_LTE.setText(_translate("MainWindow", "Open LTE..."))
        self.actionODP.setText(_translate("MainWindow", "ODP..."))
        self.actionFull_Range.setText(_translate("MainWindow", "Full Range"))
        self.actionStep_Range.setText(_translate("MainWindow", "Step Range..."))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionPSD.setText(_translate("MainWindow", "PSD"))
        self.actionPlot_3D.setText(_translate("MainWindow", "3-Component"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

