# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'station_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 764)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777214, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backwardButton = QtWidgets.QPushButton(self.frame)
        self.backwardButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/left_arr.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backwardButton.setIcon(icon)
        self.backwardButton.setObjectName("backwardButton")
        self.horizontalLayout.addWidget(self.backwardButton)
        self.intervalButton = QtWidgets.QPushButton(self.frame)
        self.intervalButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/length.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.intervalButton.setIcon(icon1)
        self.intervalButton.setObjectName("intervalButton")
        self.horizontalLayout.addWidget(self.intervalButton)
        self.forwardButton = QtWidgets.QPushButton(self.frame)
        self.forwardButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/right_arr.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon2)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.gotoButton = QtWidgets.QPushButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/go_to.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoButton.setIcon(icon3)
        self.gotoButton.setIconSize(QtCore.QSize(20, 20))
        self.gotoButton.setObjectName("gotoButton")
        self.horizontalLayout.addWidget(self.gotoButton)
        self.saveButton = QtWidgets.QPushButton(self.frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon4)
        self.saveButton.setIconSize(QtCore.QSize(16, 16))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        spacerItem = QtWidgets.QSpacerItem(452, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.infotab = QtWidgets.QWidget()
        self.infotab.setObjectName("infotab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infotab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.infotab)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.infotab, "")
        self.historytab = QtWidgets.QWidget()
        self.historytab.setObjectName("historytab")
        self.tabWidget.addTab(self.historytab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionForward = QtWidgets.QAction(MainWindow)
        self.actionForward.setObjectName("actionForward")
        self.actionBackward = QtWidgets.QAction(MainWindow)
        self.actionBackward.setObjectName("actionBackward")
        self.actionGo_to = QtWidgets.QAction(MainWindow)
        self.actionGo_to.setObjectName("actionGo_to")
        self.actionSet_interval = QtWidgets.QAction(MainWindow)
        self.actionSet_interval.setObjectName("actionSet_interval")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_event = QtWidgets.QAction(MainWindow)
        self.actionSave_event.setObjectName("actionSave_event")
        self.actionShow_info = QtWidgets.QAction(MainWindow)
        self.actionShow_info.setObjectName("actionShow_info")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionRemove_Response = QtWidgets.QAction(MainWindow)
        self.actionRemove_Response.setCheckable(True)
        self.actionRemove_Response.setObjectName("actionRemove_Response")
        self.menuFile.addAction(self.actionForward)
        self.menuFile.addAction(self.actionBackward)
        self.menuFile.addAction(self.actionGo_to)
        self.menuFile.addAction(self.actionSet_interval)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuDatabase.addAction(self.actionOpen)
        self.menuDatabase.addAction(self.actionShow_info)
        self.menuDatabase.addAction(self.actionSave_event)
        self.menuSettings.addAction(self.actionRemove_Response)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gotoButton.setText(_translate("MainWindow", "Go to..."))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infotab), _translate("MainWindow", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historytab), _translate("MainWindow", "Historial"))
        self.groupBox.setTitle(_translate("MainWindow", "Events"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionForward.setText(_translate("MainWindow", "Forward"))
        self.actionBackward.setText(_translate("MainWindow", "Backward"))
        self.actionGo_to.setText(_translate("MainWindow", "Go to..."))
        self.actionSet_interval.setText(_translate("MainWindow", "Set interval"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_event.setText(_translate("MainWindow", "Save event"))
        self.actionShow_info.setText(_translate("MainWindow", "Show info"))
        self.actionConfig.setText(_translate("MainWindow", "Config"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionRemove_Response.setText(_translate("MainWindow", "Remove Response"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
